apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roboshop-ingress
spec:
  rules:
  - host: roboshop.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
