apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roboshop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: roboshop.manojdevops897.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
